# Generated by Django 6.0.4 on 2026-06-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Commodity Prices',
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['commodity_name', 'date_recorded'], name='farm_data_c_commodi_05bc1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('commodities', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='farm_data_m_latitud_6354c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('soil_moisture', 'Soil Moisture Sensor'), ('soil_ph', 'Soil pH Sensor'), ('soil_nitrogen', 'Soil Nitrogen Sensor'), ('light', 'Light Intensity Sensor'), ('rain', 'Rain Gauge Sensor'), ('wind', 'Wind Speed Sensor'), ('multi', 'Multi-parameter Sensor')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='inactive', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('battery_level', models.PositiveIntegerField(default=100, help_text='Battery percentage')),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('measurement_interval', models.PositiveIntegerField(default=300, help_text='Seconds between measurements')),
                ('min_threshold', models.FloatField(blank=True, null=True)),
                ('max_threshold', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farm_data.sensordevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('threshold_exceeded', models.CharField(max_length=50)),
                ('expected_value', models.FloatField(null=True)),
                ('actual_value', models.FloatField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity_name', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farm_data.sensordevice')),
                ('reading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_data.sensorreading')),
            ],
            options={
                'verbose_name_plural': 'Commodity Prices',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('weather_data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weather Caches',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.AddIndex(
            model_name='sensordevice',
            index=models.Index(fields=['user', 'status'], name='farm_data_s_user_id_ccf144_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordevice',
            index=models.Index(fields=['device_id'], name='farm_data_s_device__1e05c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', 'timestamp'], name='farm_data_s_sensor__976644_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='farm_data_s_timesta_ad027b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['commodity_name', 'date_recorded'], name='farm_data_s_commodi_db13b0_idx'),
        ),
    ]
