# Generated by Django 6.0.4 on 2026-06-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('area_planted', models.FloatField(help_text='Area in hectares')),
                ('health_percentage', models.IntegerField(default=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('mature', 'Mature'), ('harvesting', 'Harvesting'), ('harvested', 'Harvested')], default='planted', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('profit_margin', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
